apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
  labels:
    app: comments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: comments-api
        image: ghcr.io/assapir/assapir.github.io:edge
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
        ports:
        - containerPort: 1337
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-params
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-params
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-params
              key: host
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
  labels:
    app: comments
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 1337
      protocol: TCP
  selector:
    app: comments
