version: '3.3'
services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
