name: Gatsby Publish

on:
  push:
    branches:
      - main

env:
  OUTPUT_DIR: 'public'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - run: npm ci
      - run: npm run format
      - run: npm run build

      - name: Copy CNAME file
        run: cp CNAME public/

      - name: Check out GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ${{ env.OUTPUT_DIR }}

      - name: 'Check for changes'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has_changes::1"
          fi
        id: status
        working-directory: ${{ env.OUTPUT_DIR }}

      - name: Publish blog
        if: steps.status.outputs.has_changes == '1'
        run: |
          git config --global user.email "me@ass.af"
          git config --global user.name "Assaf Sapir"
          git add -f .
          git commit -m "Update blog files"
          git push -f origin gh-pages
        working-directory: ${{ env.OUTPUT_DIR }}
